### PR TITLE
#19 Some data.gov csw transforms use 9999 as null date.

### PR DESCRIPTION
**Pull request by valentinedwv**
Prevents elements with 9999 at the start of a string.

### CODE REVIEW

**Comment by umacgillivray** [comment]
The for loop on data is just a check to see if there is anything to write, if the begin date is 2016-01-01 and the end date is 9999-01-01 it will publish the bad date. Probably better to check each:
```
    if (params.begin) {
      if (typeof params.begin.date === "string" && !params.begin.date.startsWith("9999")) {
        data["begin_dt"] = this.DateUtil.checkIsoDateTime(params.begin.date,false);
      }
      data["begin_indeterminate_s"] = this.Val.chkStr(params.begin.indeterminate,null);
    }
    if (params.end) {
      if (typeof params.end.date === "string" && !params.end.date.startsWith("9999")) {
        data["end_dt"] = this.DateUtil.checkIsoDateTime(params.end.date,true);
      }
      data["end_indeterminate_s"] = this.Val.chkStr(params.end.indeterminate,null);
    }
```

**Comment by umacgillivray** [comment]
Also, if you modify the indexing logic, there is a function to reindex. I'm sure there will be some scaling issues when the index gets large.

You can create an new index from an existing index (required when you modify the ES schema):
```
http://host:port/geoportal/rest/metadata/reindex?fromIndexName=metadata&toIndexName=metadata_v2
```
You can put the new index in play by pointing the "metadata" alias to the new index:
```
http://host:port/geoportal/rest/metadata/realias?indexName=metadata_v2
```
Or, you can reindex the XML documents withn the active index:
```
http://host:port/geoportal/rest/metadata/reindex?fromIndexName=metadata&toIndexName=metadata
```

Status messages will be written to the geoportal.log file during the process.

**Comment by valentinedwv** [comment]
Thanks. Just reloading a subset with the issue

**Comment by umacgillivray** [comment]
Merged. thx

**Pull request merged**
